Delete src/mbio/mbr_mr1aldeo.c:
This file was causing git to fail for me:

```console
> git clone https://github.com/dwcaress/MB-System.git
Cloning into 'MB-System'...
remote: Enumerating objects: 88602, done.
remote: Counting objects: 100% (7861/7861), done.
remote: Compressing objects: 100% (1901/1901), done.
remote: Total 88602 (delta 6065), reused 7373 (delta 5925), pack-reused 80741
Receiving objects: 100% (88602/88602), 102.89 MiB | 5.56 MiB/s, done.
Resolving deltas: 100% (76523/76523), done.
error: invalid path 'src/mbio/mbr_mr1aldeo.c:'
fatal: unable to checkout working tree
warning: Clone succeeded, but checkout failed.
You can inspect what was checked out with 'git status'
and retry with 'git restore --source=HEAD :/'
```